name: MSDO
on:
  push:
    branches:
      - main
  pull_request:  # Needed to annotate PRs with findings
    branches:
      - main

jobs:
  sample:
    name: Microsoft Security DevOps
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write  # Required for SARIF upload

    steps:
    - uses: actions/checkout@v3

    - name: Run Microsoft Security DevOps
      id: msdo
      uses: microsoft/security-devops-action@latest
      with:
        policy: GitHub  # Uses GitHub-recommended analyzers
        categories: code,artifacts,IaC,containers  # Customize as needed
        config: .github/msdo.gdnconfig

    - name: Upload SARIF results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

    - name: Upload SARIF file as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
